name: flutter_full_learn
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  
  #google
  url_launcher: ^6.1.14
  image_picker: ^1.0.4
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  google_fonts: ^6.1.0
  

  #Cache
  shared_preferences: ^2.2.1
  flutter_secure_storage: ^9.0.0

  #States
  provider: ^6.0.5
  flutter_mobx: ^2.1.1

  #core
  equatable: ^2.0.5
  collection: any
  
  #animation
  flutter_spinkit: ^5.2.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.11.0
  mobx_codegen: ^2.4.0
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/ic_app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true



flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/lottie/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

